---
num_sink_node: 10
max_dist_btw_sink_node: 50
min_dist_btw_sink_node: 10

max_communication_time: 20
min_communication_time: 10

num_uav: 4
uav_range: 50
height: 3
radius: 5

num_ants: 5
num_epochs: 20
...